version: '3'
services:
  api:
    image: demo-store-api
    command: firebase emulators:start --only functions #command: firebase serve --only functions --host 0.0.0.0
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./dot.config:/root/.config # firebase config
      - .:/opt/api
